remote_theme: chesterhow/tale

# Site settings
title:          blog
description:    "My blog. Not yours."
baseurl:        "/blog"
url:            "https://chay22.github.io"

# Google Analytics
google_analytics: UA-92790353-4

# Author
author:
  name:         Chay
  url:          https://chay22.github.io/blog
  email:        cahyadinugraha18@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
 
# Permalinks
paginate:       5
